### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by aayushdutt** [Cyber-Labs/cp-roadmap#1]
It'd be great if we had search within the website to make it easier to find something. We can use Algolia's free tier to achieve this (similar to what [Docusaurus'](https://v2.docusaurus.io/) website is doing).

**Comment by cjchirag7** [comment]
I tried to submit application for Algolia search, but they rejected it, saying they offer DocSearch for documentations of technical projects only.

**Comment by aayushdutt** [comment]
I think they have a free tier for up to 10,000 queries per month. That might be sufficient in the short run for our use-case. Could you try and see if they ask for credit card details for free usage?
https://www.algolia.com/pricing/

**Comment by cjchirag7** [comment]
Github provides 1 year subscription of algolia, in the student pack. I used that. Now, it works. Just, we would need to crawl the webpages by [Algolia Scraper](https://github.com/algolia/docsearch-scraper) and update the indices, regularly, whenever some content is added.
